name: Build Instant-Enabled App Bundle

on:
  push:
    branches:
      - masterApp  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - masterApp  # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK (Java Development Kit) - Use Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Set up Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      # Install Java XML bindings module (required for sdkmanager)
      - name: Install Java XML bindings
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2

      - name: Install JAXB
        run: |
          sudo apt-get update
          sudo apt-get install -y libjaxb-api-java
      # Install Google Play Instant Development SDK
      - name: Install Google Play Instant SDK
        run: |
          yes | $ANDROID_HOME/tools/bin/sdkmanager --sdk_root=$ANDROID_HOME "extras;google;instantapps"

      # Build the app bundle
      - name: Build App Bundle
        run: |
          ./gradlew bundleRelease

      # Upload the app bundle as an artifact
      - name: Upload App Bundle
        uses: actions/upload-artifact@v3
        with:
          name: app-bundle
          path: app/build/outputs/bundle/release/app-release.aab
